apiVersion: v1
kind: ServiceAccount
metadata:
  name: sa-ingest-api
  namespace: backend
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::727646470302:role/team1-sa-ingest-api
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: sa-matching-engine
  namespace: backend
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::727646470302:role/team1-sa-matching-engine
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: sa-recorder
  namespace: backend
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::727646470302:role/team1-sa-recorder
